### ISSUE TITLE
'action' object has no attribute 'speed'

### ISSUE THREAD

**Issue by mengqi92** [EnJiang/USV-Game#2]
运行 console.py 时报错，原因是 MyUSV 的 decision_algorithm 返回的 Action 元组没有 speed 属性。

```sh
> python console_test.py
Traceback (most recent call last):
  File "console_test.py", line 160, in <module>
    game.start()
  File "/Users/Mengqi/dev/fun/USV-Game/game.py", line 38, in start
    self.update()
  File "/Users/Mengqi/dev/fun/USV-Game/game.py", line 22, in update
    ship.move()
  File "/Users/Mengqi/dev/fun/USV-Game/usv.py", line 99, in move
    self.update_speed(action)
  File "/Users/Mengqi/dev/fun/USV-Game/usv.py", line 107, in update_speed
    self.speed = action.speed
AttributeError: 'action' object has no attribute 'speed'
```

**Comment by EnJiang** [comment]
已查明, 是因为改变了继承结构
旧 OneStepUSV -> StaticUSV
新 OneStepUSV -> BasicPlaneUSV -> StaticUSV
然后忘记覆盖OneStepUSV的move方法(它是没有update_speed这一方法的, 因为总是默认移动一格)
